name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install deps
        run: nimble install -d -y
      - name: run tests
        run: nimble test
